/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LayoutRouteImport } from "./routes/_layout"
import { Route as LayoutIndexRouteImport } from "./routes/_layout/index"
import { Route as LayoutPorQueArgentinaRouteImport } from "./routes/_layout/por-que-argentina"
import { Route as LayoutNuestraEsenciaRouteImport } from "./routes/_layout/nuestra-esencia"
import { Route as LayoutContactoRouteImport } from "./routes/_layout/contacto"
import { Route as LayoutAliadosRouteImport } from "./routes/_layout/aliados"

const LayoutRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPorQueArgentinaRoute = LayoutPorQueArgentinaRouteImport.update({
  id: "/por-que-argentina",
  path: "/por-que-argentina",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNuestraEsenciaRoute = LayoutNuestraEsenciaRouteImport.update({
  id: "/nuestra-esencia",
  path: "/nuestra-esencia",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactoRoute = LayoutContactoRouteImport.update({
  id: "/contacto",
  path: "/contacto",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAliadosRoute = LayoutAliadosRouteImport.update({
  id: "/aliados",
  path: "/aliados",
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof LayoutIndexRoute
  "/aliados": typeof LayoutAliadosRoute
  "/contacto": typeof LayoutContactoRoute
  "/nuestra-esencia": typeof LayoutNuestraEsenciaRoute
  "/por-que-argentina": typeof LayoutPorQueArgentinaRoute
}
export interface FileRoutesByTo {
  "/aliados": typeof LayoutAliadosRoute
  "/contacto": typeof LayoutContactoRoute
  "/nuestra-esencia": typeof LayoutNuestraEsenciaRoute
  "/por-que-argentina": typeof LayoutPorQueArgentinaRoute
  "/": typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_layout": typeof LayoutRouteWithChildren
  "/_layout/aliados": typeof LayoutAliadosRoute
  "/_layout/contacto": typeof LayoutContactoRoute
  "/_layout/nuestra-esencia": typeof LayoutNuestraEsenciaRoute
  "/_layout/por-que-argentina": typeof LayoutPorQueArgentinaRoute
  "/_layout/": typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    "/" | "/aliados" | "/contacto" | "/nuestra-esencia" | "/por-que-argentina"
  fileRoutesByTo: FileRoutesByTo
  to: "/aliados" | "/contacto" | "/nuestra-esencia" | "/por-que-argentina" | "/"
  id:
    | "__root__"
    | "/_layout"
    | "/_layout/aliados"
    | "/_layout/contacto"
    | "/_layout/nuestra-esencia"
    | "/_layout/por-que-argentina"
    | "/_layout/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/por-que-argentina": {
      id: "/_layout/por-que-argentina"
      path: "/por-que-argentina"
      fullPath: "/por-que-argentina"
      preLoaderRoute: typeof LayoutPorQueArgentinaRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/nuestra-esencia": {
      id: "/_layout/nuestra-esencia"
      path: "/nuestra-esencia"
      fullPath: "/nuestra-esencia"
      preLoaderRoute: typeof LayoutNuestraEsenciaRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/contacto": {
      id: "/_layout/contacto"
      path: "/contacto"
      fullPath: "/contacto"
      preLoaderRoute: typeof LayoutContactoRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/aliados": {
      id: "/_layout/aliados"
      path: "/aliados"
      fullPath: "/aliados"
      preLoaderRoute: typeof LayoutAliadosRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAliadosRoute: typeof LayoutAliadosRoute
  LayoutContactoRoute: typeof LayoutContactoRoute
  LayoutNuestraEsenciaRoute: typeof LayoutNuestraEsenciaRoute
  LayoutPorQueArgentinaRoute: typeof LayoutPorQueArgentinaRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAliadosRoute: LayoutAliadosRoute,
  LayoutContactoRoute: LayoutContactoRoute,
  LayoutNuestraEsenciaRoute: LayoutNuestraEsenciaRoute,
  LayoutPorQueArgentinaRoute: LayoutPorQueArgentinaRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
